#ifndef XKILL_RENDERER_GBUFFERID_H
#define XKILL_RENDERER_GBUFFERID_H

enum GBufferID
{
	GBUFFERID_NORMAL,
	GBUFFERID_ALBEDO,
	GBUFFERID_MATERIAL,

	GBUFFERID_NUM_BUFFERS
};

#endif //XKILL_RENDERER_GBUFFERID_H