#pragma once

enum InputBoolAction
{
	ACTION_B_FIRE,
	ACTION_B_CHANGE_AMMUNITIONTYPE,
	ACTION_B_CHANGE_FIRINGMODE,
	ACTION_B_WALK_LEFT,
	ACTION_B_WALK_RIGHT,
	ACTION_B_WALK_FORWARD,
	ACTION_B_WALK_BACKWARD,
	ACTION_B_LOOK_UP,
	ACTION_B_LOOK_DOWN,
	ACTION_B_LOOK_LEFT,
	ACTION_B_LOOK_RIGHT,
	ACTION_B_RUMBLE_ON,
	ACTION_B_RUMBLE_OFF,
	ACTION_B_TOGGLE_MUTE_SOUND,

	ACTION_B_LAST
};

enum InputFloatAction
{
	ACTION_F_LOOK_LR,
	ACTION_F_LOOK_UD,
	ACTION_F_WALK_FB,
	ACTION_F_WALK_LR,

	ACTION_F_LAST
};