#ifndef XKILL_UTILITIES_LIGHTSTRUCTS_H
#define XKILL_UTILITIES_LIGHTSTRUCTS_H

enum LightType
{ 
	LIGHTTYPE_DIRECTIONAL	= 0, 
	LIGHTTYPE_POINT			= 1, 
	LIGHTTYPE_SPOT			= 2, 
	LIGHTTYPE_NA			= 3
};

#endif //XKILL_UTILITIES_LIGHTSTRUCTS_H